[project]
name = "altron-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "TheAdaptoid", email = "mhwkmn22@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["altron-types"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
altron-types = { workspace = true }
